version: '3'

services:
  java:
    image: java-mysql:1.0
    restart: always
    environment:
      
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: java-mysql
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: java-mysql
volumes:
  db_data:
